# Generated by Django 5.2.4 on 2025-07-31 12:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hanich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='תעודת זהות')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='שם פרטי')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='שם משפחה')),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='שם הורה')),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון הורה')),
                ('second_parent_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון הורה נוסף')),
                ('personal_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון חניך')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל')),
                ('gender', models.CharField(blank=True, choices=[('male', 'זכר'), ('female', 'נקבה')], max_length=10, null=True, verbose_name='מגדר')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='תאריך לידה')),
                ('mahoz', models.CharField(blank=True, max_length=50, null=True, verbose_name='מחוז')),
                ('ken', models.CharField(blank=True, max_length=50, null=True, verbose_name='קן')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='כיתה')),
                ('food_preference', models.CharField(blank=True, choices=[('meat', 'בשרי/ת'), ('meat_gluten_free', 'בשרי/ת ללא גלוטן'), ('vegan', 'טבעוני/ת'), ('vegan_gluten_free', 'טבעוני/ת ללא גלוטן'), ('vegetarian', 'צמחוני/ת'), ('vegetarian_gluten_free', 'צמחוני/ת ללא גלוטן')], max_length=50, null=True, verbose_name='העדפת תזונה')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='תאריך הרשמה')),
                ('registration_time', models.TimeField(blank=True, null=True, verbose_name='שעת הרשמה')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='בוטל')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalHanich',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('personal_id', models.CharField(blank=True, db_index=True, max_length=9, null=True, verbose_name='תעודת זהות')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='שם פרטי')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='שם משפחה')),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='שם הורה')),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון הורה')),
                ('second_parent_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון הורה נוסף')),
                ('personal_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון חניך')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל')),
                ('gender', models.CharField(blank=True, choices=[('male', 'זכר'), ('female', 'נקבה')], max_length=10, null=True, verbose_name='מגדר')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='תאריך לידה')),
                ('mahoz', models.CharField(blank=True, max_length=50, null=True, verbose_name='מחוז')),
                ('ken', models.CharField(blank=True, max_length=50, null=True, verbose_name='קן')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='כיתה')),
                ('food_preference', models.CharField(blank=True, choices=[('meat', 'בשרי/ת'), ('meat_gluten_free', 'בשרי/ת ללא גלוטן'), ('vegan', 'טבעוני/ת'), ('vegan_gluten_free', 'טבעוני/ת ללא גלוטן'), ('vegetarian', 'צמחוני/ת'), ('vegetarian_gluten_free', 'צמחוני/ת ללא גלוטן')], max_length=50, null=True, verbose_name='העדפת תזונה')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='תאריך הרשמה')),
                ('registration_time', models.TimeField(blank=True, null=True, verbose_name='שעת הרשמה')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='בוטל')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical hanich',
                'verbose_name_plural': 'historical hanichs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
