# Generated by Django 5.2.4 on 2025-07-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanich',
            options={'verbose_name': 'חניך', 'verbose_name_plural': 'חניכים'},
        ),
        migrations.AlterModelOptions(
            name='historicalhanich',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical חניך', 'verbose_name_plural': 'historical חניכים'},
        ),
    ]
