# Generated by Django 5.2.4 on 2025-07-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0002_alter_hanich_options_alter_historicalhanich_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanich',
            name='grade',
            field=models.CharField(blank=True, null=True, verbose_name='כיתה'),
        ),
        migrations.AlterField(
            model_name='hanich',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='ביטל הרשמה'),
        ),
        migrations.AlterField(
            model_name='historicalhanich',
            name='grade',
            field=models.CharField(blank=True, null=True, verbose_name='כיתה'),
        ),
        migrations.AlterField(
            model_name='historicalhanich',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='ביטל הרשמה'),
        ),
    ]
