# Generated by Django 5.2.4 on 2025-07-31 13:46

from django.db import migrations

from hamal_bmosh.setup.mahozot import mahozot_list


def add_bmosh_mahozot(apps, schema_editor):
    Mahoz = apps.get_model("hamal_bmosh", "Mahoz")
    for mahoz in mahozot_list:
        new_mahoz = Mahoz.objects.create(mahoz_code=mahoz["code_mahoz"], mahoz_name=mahoz["name"])


class Migration(migrations.Migration):
    dependencies = [
        ('hamal_bmosh', '0004_mahoz_historicalmahoz_ken_historicalken'),
    ]

    operations = [
        migrations.RunPython(add_bmosh_mahozot, migrations.RunPython.noop)
    ]
