# Generated by Django 5.2.4 on 2025-07-31 14:08

from django.db import migrations

from hamal_bmosh.setup.kenim import kenim_list


def add_kenim(apps, schema_editor):
    Ken = apps.get_model("hamal_bmosh", "Ken")
    Mahoz = apps.get_model("hamal_bmosh","Mahoz")
    for ken in kenim_list:
        mahoz = Mahoz.objects.get(mahoz_code=ken["mahoz"])
        new_ken = Ken.objects.create(ken_code=ken["ken_code"], ken_name=ken["name"], mahoz=mahoz)


class Migration(migrations.Migration):
    dependencies = [
        ('hamal_bmosh', '0005_add_mahozot'),
    ]

    operations = [
        migrations.RunPython(add_kenim, migrations.RunPython.noop)
    ]
