# Generated by Django 5.2.4 on 2025-07-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0006_add_kenim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanich',
            name='mahoz',
        ),
        migrations.RemoveField(
            model_name='historicalhanich',
            name='mahoz',
        ),
    ]
