# Generated by Django 5.2.4 on 2025-07-31 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0007_remove_hanich_mahoz_remove_historicalhanich_mahoz'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanich',
            name='mahoz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hamal_bmosh.mahoz', verbose_name='מחוז'),
        ),
        migrations.AddField(
            model_name='historicalhanich',
            name='mahoz',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hamal_bmosh.mahoz', verbose_name='מחוז'),
        ),
    ]
