# Generated by Django 5.2.4 on 2025-07-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0008_hanich_mahoz_historicalhanich_mahoz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanich',
            name='ken',
        ),
        migrations.RemoveField(
            model_name='historicalhanich',
            name='ken',
        ),
    ]
