# Generated by Django 5.2.4 on 2025-07-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0009_remove_hanich_ken_remove_historicalhanich_ken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[("א'", 'First'), ("ב'", 'Second'), ("ג'", 'Third'), ("ד'", 'Fourth'), ("ה'", 'Fifth'), ("ו'", 'Sixth'), ("ז'", 'Seventh'), ("ח'", 'Eighth'), ("ט'", 'Ninth'), ("י'", 'Tenth'), ('י"א', 'Eleventh'), ('י"ב', 'Twelfth'), ('י"ג', 'Thirteenth'), ('י"ד', 'Fourteenth'), ('מבוגרים', 'Adult')], max_length=45, null=True, verbose_name='כיתה')),
            ],
            options={
                'verbose_name': 'כיתה',
                'verbose_name_plural': 'כיתות',
            },
        ),
        migrations.AddField(
            model_name='hanich',
            name='ken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hamal_bmosh.ken', verbose_name='קן'),
        ),
        migrations.AddField(
            model_name='historicalhanich',
            name='ken',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hamal_bmosh.ken', verbose_name='קן'),
        ),
    ]
