# Generated by Django 5.2.4 on 2025-07-31 14:58

from django.db import migrations

from hamal_bmosh.choices import GradeNameChoices


def add_grades(apps, schema_editor):
    Grade = apps.get_model("hamal_bmosh", "Grade")
    for grade in GradeNameChoices:
        new_grade = Grade.objects.create(name=grade)

class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0010_grade_hanich_ken_historicalhanich_ken'),
    ]

    operations = [
        migrations.RunPython(add_grades, migrations.RunPython.noop)
    ]
