# Generated by Django 5.2.4 on 2025-07-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0011_add_grades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'שכבה', 'verbose_name_plural': 'שכבות'},
        ),
        migrations.RemoveField(
            model_name='hanich',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='historicalhanich',
            name='grade',
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(blank=True, choices=[("א'", "א'"), ("ב'", "ב'"), ("ג'", "ג'"), ("ד'", "ד'"), ("ה'", "ה'"), ("ו'", "ו'"), ("ז'", "ז'"), ("ח'", "ח'"), ("ט'", "ט'"), ("י'", "י'"), ('י"א', 'י"א'), ('י"ב', 'י"ב'), ('י"ג', 'י"ג'), ('י"ד', 'י"ד'), ('מבוגרים', 'מבוגרים')], max_length=45, null=True, verbose_name='שכבה'),
        ),
    ]
