# Generated by Django 5.2.4 on 2025-07-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0012_alter_grade_options_remove_hanich_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanich',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hamal_bmosh.grade', verbose_name='שכבה'),
        ),
        migrations.AddField(
            model_name='historicalhanich',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hamal_bmosh.grade', verbose_name='שכבה'),
        ),
    ]
