# Generated by Django 5.2.4 on 2025-08-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0013_hanich_grade_historicalhanich_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHanich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='סטטוס')),
                ('active_status', models.BooleanField(default=True, verbose_name='סטטוס פעיל')),
            ],
            options={
                'verbose_name': 'סטטוס חניך',
                'verbose_name_plural': 'סטטוס חניכים',
            },
        ),
        migrations.AddField(
            model_name='hanich',
            name='arrived_to_the_event',
            field=models.BooleanField(default=False, verbose_name='הגיע לאירוע'),
        ),
        migrations.AddField(
            model_name='historicalhanich',
            name='arrived_to_the_event',
            field=models.BooleanField(default=False, verbose_name='הגיע לאירוע'),
        ),
    ]
