# Generated by Django 5.2.4 on 2025-08-03 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0014_statushanich_hanich_arrived_to_the_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanich',
            name='status_hanich',
            field=models.ForeignKey(blank=True, limit_choices_to={'active_status': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hamal_bmosh.statushanich', verbose_name='סטטוס חניך'),
        ),
        migrations.AddField(
            model_name='historicalhanich',
            name='status_hanich',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active_status': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hamal_bmosh.statushanich', verbose_name='סטטוס חניך'),
        ),
    ]
