# Generated by Django 5.2.4 on 2025-08-03 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0015_hanich_status_hanich_historicalhanich_status_hanich'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='מספר אוטובוס')),
                ('direction', models.CharField(choices=[('הולך', 'הלוך'), ('חוזר', 'חזור'), ('אחר', 'אחר')], max_length=10, verbose_name='כיוון')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='חברת הסעה')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='שם הנהג')),
                ('driver_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון נהג')),
                ('escort_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='אחראי נסיעה')),
                ('escort_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון אחראי נסיעה')),
            ],
            options={
                'verbose_name': 'אוטובוס',
                'verbose_name_plural': 'אוטובוסים',
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='תאריך')),
                ('name', models.CharField(max_length=100, verbose_name='שם התחנה')),
                ('arrival_time', models.TimeField(verbose_name='שעת התייצבות')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='hamal_bmosh.bus', verbose_name='אוטובוס')),
            ],
            options={
                'verbose_name': 'תחנת איסוף',
                'verbose_name_plural': 'תחנות איסוף',
                'ordering': ['arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='HanichBusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamal_bmosh.bus', verbose_name='אוטובוס')),
                ('hanich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamal_bmosh.hanich', verbose_name='חניך')),
            ],
            options={
                'unique_together': {('hanich', 'bus')},
            },
        ),
    ]
