# Generated by Django 5.2.4 on 2025-08-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0016_bus_busstop_hanichbusassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hanichbusassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bus',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך'),
        ),
    ]
