# Generated by Django 5.2.4 on 2025-08-03 12:59

from django.db import migrations

from hamal_bmosh.setup.statuses import status_list


def add_statuses(apps, schema_editor):
    StatusHanich = apps.get_model("hamal_bmosh", "StatusHanich")
    for status in status_list:
        new_status = StatusHanich.objects.create(status=status)

class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0017_alter_hanichbusassignment_unique_together_bus_date'),
    ]

    operations = [
        migrations.RunPython(add_statuses, migrations.RunPython.noop)
    ]
