# Generated by Django 5.2.4 on 2025-08-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0018_add_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanichbusassignment',
            options={'verbose_name': 'שיוך חניך לאוטובוס', 'verbose_name_plural': 'שיוך חניכים לאוטובוס'},
        ),
        migrations.CreateModel(
            name='HanichExtraQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='שאלה')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='תשובה')),
                ('hanich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_questions', to='hamal_bmosh.hanich', verbose_name='חניך')),
            ],
            options={
                'verbose_name': 'שאלה נוספת',
                'verbose_name_plural': 'שאלות נוספות',
            },
        ),
    ]
