# Generated by Django 5.2.4 on 2025-08-07 10:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0019_alter_hanichbusassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='תאריך')),
                ('number', models.CharField(max_length=20, verbose_name='מספר אוטובוס')),
                ('direction', models.CharField(choices=[('הולך', 'הלוך'), ('חוזר', 'חזור'), ('אחר', 'אחר')], max_length=10, verbose_name='כיוון')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='חברת הסעה')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='שם הנהג')),
                ('driver_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון נהג')),
                ('escort_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='אחראי נסיעה')),
                ('escort_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון אחראי נסיעה')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical אוטובוס',
                'verbose_name_plural': 'historical אוטובוסים',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBusStop',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='תאריך')),
                ('name', models.CharField(max_length=100, verbose_name='שם התחנה')),
                ('arrival_time', models.TimeField(verbose_name='שעת התייצבות')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bus', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hamal_bmosh.bus', verbose_name='אוטובוס')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical תחנת איסוף',
                'verbose_name_plural': 'historical תחנות איסוף',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGrade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[("א'", "א'"), ("ב'", "ב'"), ("ג'", "ג'"), ("ד'", "ד'"), ("ה'", "ה'"), ("ו'", "ו'"), ("ז'", "ז'"), ("ח'", "ח'"), ("ט'", "ט'"), ("י'", "י'"), ('י"א', 'י"א'), ('י"ב', 'י"ב'), ('י"ג', 'י"ג'), ('י"ד', 'י"ד'), ('מבוגרים', 'מבוגרים')], max_length=45, null=True, verbose_name='שכבה')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical שכבה',
                'verbose_name_plural': 'historical שכבות',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHanichExtraQuestion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='שאלה')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='תשובה')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hanich', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hamal_bmosh.hanich', verbose_name='חניך')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical שאלה נוספת',
                'verbose_name_plural': 'historical שאלות נוספות',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStatusHanich',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='סטטוס')),
                ('active_status', models.BooleanField(default=True, verbose_name='סטטוס פעיל')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical סטטוס חניך',
                'verbose_name_plural': 'historical סטטוס חניכים',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
