# Generated by Django 5.2.4 on 2025-08-07 10:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0020_historicalbus_historicalbusstop_historicalgrade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='שם אירוע')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='תחילת אירוע')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='סיום אירוע')),
            ],
            options={
                'verbose_name': 'אירוע',
                'verbose_name_plural': 'אירועים',
                'constraints': [models.UniqueConstraint(fields=('event_name', 'start_date'), name='unique_event_name_start_date')],
            },
        ),
        migrations.CreateModel(
            name='EventRosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosh_name', models.CharField(max_length=100, verbose_name='שם הראש')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rashim', to='hamal_bmosh.event', verbose_name='אירוע')),
            ],
            options={
                'verbose_name': 'ראש',
                'verbose_name_plural': 'ראשים',
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='שם קבוצה')),
                ('rosh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='hamal_bmosh.eventrosh', verbose_name='ראש')),
            ],
            options={
                'verbose_name': 'קבוצה באירוע',
                'verbose_name_plural': 'קבוצות באירוע',
            },
        ),
        migrations.CreateModel(
            name='HanichInEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registration_time', models.TimeField(blank=True, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hanichim', to='hamal_bmosh.event')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hanichim', to='hamal_bmosh.eventgroup')),
                ('hanich', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='hamal_bmosh.hanich')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='שם אירוע')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='תחילת אירוע')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='סיום אירוע')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical אירוע',
                'verbose_name_plural': 'historical אירועים',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEventGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='שם קבוצה')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rosh', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hamal_bmosh.eventrosh', verbose_name='ראש')),
            ],
            options={
                'verbose_name': 'historical קבוצה באירוע',
                'verbose_name_plural': 'historical קבוצות באירוע',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEventRosh',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rosh_name', models.CharField(max_length=100, verbose_name='שם הראש')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hamal_bmosh.event', verbose_name='אירוע')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ראש',
                'verbose_name_plural': 'historical ראשים',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='eventrosh',
            constraint=models.UniqueConstraint(fields=('event', 'rosh_name'), name='unique_event_rosh_name'),
        ),
        migrations.AddConstraint(
            model_name='eventgroup',
            constraint=models.UniqueConstraint(fields=('rosh', 'group_name'), name='unique_group_per_rosh'),
        ),
        migrations.AddConstraint(
            model_name='hanichinevent',
            constraint=models.UniqueConstraint(fields=('hanich', 'event'), name='unique_hanich_per_event'),
        ),
    ]
