# Generated by Django 5.2.4 on 2025-08-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0021_event_eventrosh_eventgroup_hanichinevent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanichinevent',
            options={'verbose_name': 'חניך באירוע', 'verbose_name_plural': 'חניכים באירועים'},
        ),
    ]
