# Generated by Django 5.2.4 on 2025-08-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0022_alter_hanichinevent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanichinevent',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='hanichinevent',
            name='registration_time',
        ),
    ]
