# Generated by Django 5.2.4 on 2025-08-07 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0023_remove_hanichinevent_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanichinevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hanichim', to='hamal_bmosh.event', verbose_name='אירוע'),
        ),
        migrations.AlterField(
            model_name='hanichinevent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hanichim', to='hamal_bmosh.eventgroup', verbose_name='קבוצה באירוע'),
        ),
        migrations.AlterField(
            model_name='hanichinevent',
            name='hanich',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='hamal_bmosh.hanich', verbose_name='חניך'),
        ),
    ]
