# Generated by Django 5.2.4 on 2025-08-07 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamal_bmosh', '0025_historicalhanichinevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanichextraquestion',
            name='hanich',
        ),
        migrations.RemoveField(
            model_name='historicalhanichextraquestion',
            name='hanich',
        ),
        migrations.AddField(
            model_name='hanichextraquestion',
            name='hanich_in_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extra_questions', to='hamal_bmosh.hanichinevent', verbose_name='חניך'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalhanichextraquestion',
            name='hanich_in_event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hamal_bmosh.hanichinevent', verbose_name='חניך'),
        ),
    ]
