# Generated by Django 5.2.4 on 2025-08-20 10:40

from django.db import migrations

from mifal_management.setup.mahozot import mahozot_list


def add_mahozot(apps, schema_editor):
    Mahoz = apps.get_model("mifal_management", "Mahoz")
    for mahoz in mahozot_list:
        new_mahoz = Mahoz.objects.create(mahoz_code=mahoz["code_mahoz"], mahoz_name=mahoz["name"])


class Migration(migrations.Migration):
    dependencies = [
        ('mifal_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_mahozot, migrations.RunPython.noop)
    ]
