# Generated by Django 5.2.4 on 2025-08-20 10:41

from django.db import migrations

from mifal_management.setup.kenim import kenim_list


def add_kenim(apps, schema_editor):
    Ken = apps.get_model("mifal_management", "Ken")
    Mahoz = apps.get_model("mifal_management", "Mahoz")
    for ken in kenim_list:
        mahoz = Mahoz.objects.get(mahoz_code=ken["mahoz"])
        new_ken = Ken.objects.create(ken_code=ken["ken_code"], ken_name=ken["name"], mahoz=mahoz)


class Migration(migrations.Migration):
    dependencies = [
        ('mifal_management', '0002_add_mahozot'),
    ]

    operations = [
        migrations.RunPython(add_kenim, migrations.RunPython.noop)
    ]
