# Generated by Django 5.2.4 on 2025-08-20 10:42

from django.db import migrations

from mifal_management.choices import GradeNameChoices


def add_grades(apps, schema_editor):
    Grade = apps.get_model("mifal_management", "Grade")
    for grade in GradeNameChoices:
        new_grade = Grade.objects.create(name=grade)


class Migration(migrations.Migration):
    dependencies = [
        ('mifal_management', '0003_add_kenim'),
    ]

    operations = [
        migrations.RunPython(add_grades, migrations.RunPython.noop)
    ]
