# Generated by Django 5.2.4 on 2025-08-20 10:42

from django.db import migrations

from mifal_management.setup.statuses import status_list


def add_statuses(apps, schema_editor):
    StatusHanich = apps.get_model("mifal_management", "StatusHanich")
    for status in status_list:
        new_status = StatusHanich.objects.create(status=status)


class Migration(migrations.Migration):
    dependencies = [
        ('mifal_management', '0004_add_grades'),
    ]

    operations = [
        migrations.RunPython(add_statuses, migrations.RunPython.noop)
    ]
